### ISSUE TITLE
Upable to log on to the Influx DB

### ISSUE THREAD

**Issue by drguptavivek** [haidlir/jitsi-monitoring#1]
I have installed the docker container and those up up and running. Since teh installation was done on a server, i logged on to the Grafana interface from another dektop using
http://serverIP:3000/

I tried using the INFLUXDB passwords given in .env file
However, I am not able to log in.

**Comment by haidlir** [comment]
Thanks for the question @drguptavivek ,

To log in into Grafana, you can use the password assigned in grafana service's environment within docker-compose.yaml file.
https://github.com/haidlir/jitsi-monitoring/blob/2f6e08dcd651988afad039c045acbdc7e43ca0ca/docker-compose.yaml#L60
In this case.
username: admin
password: pass

**Comment by drguptavivek** [comment]
Thanks !
